spring:
  application:
    name: project_generator
  profiles:
    active: local
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000

  data:
    redis:
      host: your redis host
      port:
      password: your redis password
      ttl: 3600
      user-name: your redis user



server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ai.project.project_generator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn



langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: xxxxx
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-mode: true
      response-format:
        type: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-reasoner
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true

#  community:
#    redis :
#      enabled: false
#      host: 127.0.0.1
#      port: 6379
#      password:
#      dimension: 384
# Pexels 图片搜索配置
pexels:
  api-key: your api key

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your host
    secretId: your secretId
    secretKey: your secretKey
    region: your region
    bucket: your bucket name
# 阿里云 DashScope 配置
dashscope:
  api-key: your key
  image-model: wan2.2-t2i-flash
